name: Deployment Pipeline

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.24.79.29 << 'EOF'
            cd /home/ubuntu/app || git clone https://github.com/Godwin-T/fastapi-book-project.git app && cd app
            git pull origin main
            if lsof -i:8000; then
              docker stop $(docker container ls --filter "publish=8000" -q)
            fi
            docker build -t fastapi-app . && docker run -d -p 8000:8000 fastapi-app
          EOF
